name: dependabot-alerts-action
description: List the Dependabot alerts for a repository

inputs:
  path:
    description: Glob pattern of the file path to check for alerts
    required: true
  package-ecosystem:
    description: List of package ecosystems (e.g. `NPM`)
    required: true
  token:
    description: GitHub Token
    required: true
    default: ${{ github.token }}

outputs:
  dependency-files-json:
    description: JSON array of dependency file paths with Dependabot alerts
  packages-lines:
    description: Multiline string in the format of `package-name@version`
  packages-json:
    description: JSON object with package names as keys and versions as values

runs:
  using: 'node20'
  main: 'dist/index.js'
